"""Workflow helpers for generated dataset access probes."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Sequence

from backend.access_probes.runner import PROBE_SCRIPT_NAME
from backend.agents.access_probe.agent import AccessProbeGenerationAgent
from backend.agents.contract_drafting.workflow import DatasetContractRun
from backend.llm import LLMClient


def _strip_code_fence(code: str) -> str:
    text = code.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    return text


def _validate_probe_script(code: str) -> str:
    normalized = _strip_code_fence(code).rstrip() + "\n"
    try:
        compile(normalized, PROBE_SCRIPT_NAME, "exec")
    except SyntaxError as error:
        raise ValueError(f"Generated {PROBE_SCRIPT_NAME} is not valid Python: {error}") from error

    if not re.search(r"\bjson\.dumps\b|\bjson\.dump\b", normalized):
        raise ValueError(f"Generated {PROBE_SCRIPT_NAME} must print a JSON result.")
    return normalized


def ensure_access_probe_script(
    *,
    dataset_slug: str,
    run: DatasetContractRun,
    dataset_dir: Path,
    credential_requirements: Sequence[Any],
    timeout_seconds: int = 180,
    force: bool = False,
) -> tuple[Path, bool]:
    """Create project-local access_probe.py with an LLM agent when it is missing."""

    dataset_dir.mkdir(parents=True, exist_ok=True)
    script_path = dataset_dir / PROBE_SCRIPT_NAME
    if script_path.exists() and not force:
        return script_path, False

    requirements = [
        item.model_dump(mode="json") if hasattr(item, "model_dump") else item for item in credential_requirements
    ]
    generated = AccessProbeGenerationAgent(LLMClient(timeout_seconds=timeout_seconds)).create_access_probe_script(
        dataset_slug=dataset_slug,
        run=run,
        credential_requirements=requirements,
    )
    code = _validate_probe_script(generated.python_code)
    header = (
        "# Generated by AccessProbeGenerationAgent.\n"
        "# Dataset-specific project code: keep secrets in environment variables only.\n"
    )
    script_path.write_text(header + code, encoding="utf-8")
    metadata_path = dataset_dir / "access_probe.metadata.json"
    metadata_path.write_text(
        json.dumps(generated.model_dump(mode="json", exclude={"python_code"}), indent=2) + "\n",
        encoding="utf-8",
    )
    return script_path, True
